################################################################################
# Set the base image to nginx
################################################################################

FROM nginx:1.11

MAINTAINER "Abhijeet Kohakade" <abhijeet.kohakade@selenite.co>

RUN apt-get update

#COPY nginx.conf /etc/nginx/nginx.conf

###############################################################################